//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.0.3.0 (NJsonSchema v9.12.5.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using Newtonsoft.Json;

namespace Esys.Thingsboard.Clients
{
    public class AdditionalInfo
    {
        [JsonProperty("lang")]
        public string Lang { get; set; }
    }
}